### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#10]
Redo the gh-pages for better documentation of all the bundlers. Make separate versions for all major versions.

**Comment by shawnrice** [comment]
So, we've been documenting the code so that we can use common tools to pull out the documentation. We have an issue that we need to sort out in that each of these will create very different documentation as they are all self-contained. We need some sort of way to unify them -- aesthetically -- so that our docs don't look so fragmented.

Next, we need to write the sort of "tutorial" documentation for each bundler along with a conceptual overview and examples.

Lastly, we need to setup the structure so that the documentation will support multiple major versions with the newest being the default.

Any ideas?

We could always take advantage of the wiki if that would be the better way to go.

**Comment by stephen-bunn** [comment]
If your looking for an autodoc generation setup, there are a few that support all the languages currently in the bundler. 

If any I would recommend [HeaderDoc](https://www.google.com/url?sa=t&source=web&cd=3&ved=0CBEQFjAC&url=https%3A%2F%2Fdeveloper.apple.com%2Flibrary%2Fmac%2Fdocumentation%2FDeveloperTools%2FConceptual%2FHeaderDoc%2FHeaderDoc.pdf&ei=zszWU6GdFdDJsQSt8YK4Dw&usg=AFQjCNF01BsEu8tuWY9-2GuFSxZqnqkTyg&sig2=fyIKPZMPnh8QVtbO8AICQw). It's built for Xcode, but can be used in the command line. 

I've not used it much, but a lot of my colleagues do.

**Comment by shawnrice** [comment]
Hm. I just did more of a looksey as well, and it seems that Sphinx can actually do [Ruby](https://github.com/thewtex/sphinx-contrib/tree/master/rubydomain) and [PHP](https://pypi.python.org/pypi/sphinxcontrib-phpdomain). Both plugins look a bit old.

There is also [Natural Docs](http://www.naturaldocs.org).

I'll look a bit more at HeaderDoc to see. I know that it might be hard to get Dean away from Sphinx (for good reasons).

**Comment by stephen-bunn** [comment]
I much rather use Sphinx than HeaderDoc or NaturalDocs. So if we narrow down to Sphinx, I'll be happy.

**Comment by deanishe** [comment]
The Python bundler (well, wrapper) is documented in detail in Sphinx within the source code.

The problem is extracting/generating that documentation in a fashion that is consistent with the bundler/other wrappers.

**Comment by deanishe** [comment]
FWIW, I also have demo workflows for Aries _and_ Taurus that are very heavily documented. Documented in the sense of comments, not HTML, mind you.

**Comment by shawnrice** [comment]
It's worth a lot. We should modify the Taurus workflow so as to have an implementation of each version of the bundler in it so as to consolidate them. We should also include one in a non-bundler language, like AppleScript so that we can show people how to use the misc bundler from the outside.

**Comment by shawnrice** [comment]
Proposal:

If we can't get Sphinx to work (or another one) **easily** with all versions of the bundler, then we just use whichever native source documentation generators there are for each language (haven't found one for bash, unsurprisingly). Instead, what we can do is just setup an `iframe` in the documentation page and load the generated, source documentation in that `iframe`. I hate using those, but this issue looks like it could substantially delay the release of Taurus, which isn't worth it.

The `iframe` will serve its purpose, and we can always revisit the subject at any point for updates because, well, it doesn't matter if we change it.

**Comment by deanishe** [comment]
My personal preference (as you can probably guess) is to use whatever is most appropriate for each language.

Certainly with Python, the expectation that [docstrings](http://en.wikipedia.org/wiki/Docstring#Python) will be used for documenting your code is approximately 100%, although exactly what format the docstrings should take is an entirely different matter…

Neither Natural Docs nor HeaderDoc use docstrings (one expects pseudo-docstrings _above_ the corresponding function/method/class definition (???), and the other wants #-style comments).

I think we should rather concentrate on finding/creating themes (I assume all the systems we're talking about support HTML themes) that make the generated HTML files look similar.

Solarized/Bootstrap might be a good place to start looking: both are very popular.

Don't know about Solarized, but it's definitely possible to generate Python/Sphinx docs using Bootstrap and [bootswatches](http://bootswatch.com/).

**Comment by shawnrice** [comment]
Btw: I've been writing some of the generic documentation on the wiki such as a page on bundler [terminology](https://github.com/shawnrice/alfred-bundler/wiki/Terminology).

I figure we can edit these together and then include them in the documentation pages (not as links). Consider them an easy place to develop the documentation.

**Comment by shawnrice** [comment]
We could use the [Docco](https://jashkenas.github.io/docco/) family, I have mixed feelings about it....
- [Shocco](https://rtomayko.github.io/shocco/)
- [sourceMakeup](http://jquery-jkit.com/sourcemakeup/)
- [Pycco](https://fitzgen.github.io/pycco/)
- [Rocco](https://rtomayko.github.io/rocco/rocco.html)

We could tweak the CSS so that they'd all look the same, but, again, I'm not too sure how I feel about this kind of annotated format.

**Comment by shawnrice** [comment]
So, I spent way too long playing around with Jekyll trying to get a nice way to make the docs integrate with that, and I gave up. I started a temporary repo called "bundler-docs" to create the new `gh-pages` site. https://shawnrice.github.io/bundler-docs/

**Comment by shawnrice** [comment]
Since this is close-ish to completion, and since it has its own repo, and since it's tracked in #65, I'm closing.
