### ISSUE TITLE
Create Fallback Server for Icons

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#11]

**Comment by shawnrice** [comment]
Here's @deanishe's [repo](https://github.com/deanishe/bundler-icon-server). I'm putting this here for my benefit. I'm unassigning myself for a couple of days as well (computer is in the shop and using my gf's computer) because access to all my pub keys, etc... for my servers is a bit inconvenient right now.

**Comment by deanishe** [comment]
Could you send the icons (and HTML?), so I can update the Iconserver?

Any preference for where we put the alternate server(s)?

**Comment by shawnrice** [comment]
##### Icons / HTML

I can do that shortly. Double-check this:

for the html, we just need 
1. a table with four columns (name, 10.10, 10.9, 10.8) and a header
2. a class on each name cell
3. a class on each icon cell
4. a class on each row
5. a class on the table header
6. a class on the table
7. a class on each icon image...
8. Icons at 48px and 96 (48px@2x.png)

What should the directory structure be? I.e., where should the icon paths be pointing?

Anything else? Do you want any other standard classes on them? Do you just want the table as such with the icons and nothing else?

##### Server Locations

I can set one up on the Packal server, with a subdomain
I could also set one up on the Packal dev server, but that one is a bit volatile because I use it to break things...

##### Setup files

I know you have the repo, but can you send me the other files I'll need (i.e. the fonts that aren't on there). Can you also send me a sample nginx config file?

Is there anything else I should need to set it up past the instructions on the repo and those extra files?

**Comment by shawnrice** [comment]
Icon server has been updated to show system icons.
