### ISSUE TITLE
Alter JSON Structure

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#14]
Add in two flags for _utilities_:
1. gatekeeper : true/false
2. message : 'explanation of what the utility does'

The message will be shown when requesting gatekeeper permissions so as to give more information during the installation process to reassure users of what the utility will do.

As far as I know, Gatekeeper is invoked only when using the `open` command from the CLI, so the Gatekeeper script needs to be called much less often than it already does. However, this needs confirmation.

**Other Flags**
Are there any other flags that we should implement? Or should we change the JSON structure entirely? This needs to be sorted out before Taurus.

**Comment by deanishe** [comment]
IMO, the most important issue right now is ensuring that GK only gets called once.

We've had problems with that so far, and fixing that has to be the no. 1 priority.

A proper explanation of why we need the user's permission/password is a given.

**Comment by shawnrice** [comment]
The two fields mentioned above should take care of the messages and calling it only on things that actually really need it. We can re-implement the caching across all the bundlers to make sure it's called only once (well, called until it is accepted).

**Comment by shawnrice** [comment]
If there isn't anything else that seems necessary, then should we close this issue?

**Comment by shawnrice** [comment]
Closing this. Seems like there are no further edits needed for now (pending consensus on #36).
