### ISSUE TITLE
Bash Coding Style

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#16]
As indicated in the README.md file, Bash code should follow [Google's Shell Style Guide](https://google-styleguide.googlecode.com/svn/trunk/shell.xml). So, we need to convert the following files:
- [x] `bundler/AlfredBundler.sh`
- [x] `bundler/uninstall.sh`
- [x] `bundler/includes/gatekeeper.sh`
- [x] `bundler/includes/helper-functions.sh`
- [x] `bundler/includes/png_to_icns.sh`
- [x] `bundler/includes/icns_to_png.sh`
- [x] `bundler/meta/fork.sh`
- [x] `bundler/meta/installer.sh`
- [x] `bundler/meta/update-wrapper.sh`
- [x] `bundler/meta/update.sh`
- [x] `bundler/meta/updates/update_bundler_data_structure.sh`
- [x] `bundler/wrappers/alfred.bundler.sh`
- [x] `bundler/wrappers/alfred.bundler.misc.sh`

**Comment by shawnrice** [comment]
Actually, this is up for debate. We can choose another one if we want.

**Comment by deanishe** [comment]
By my reading, that means we have to:
- rename functions to use underscores, not CamelCase
- add `main` functions where appropriate
- add comments, esp. at the top of the files
- improve checking of return values
- provide more informative return values

**Comment by shawnrice** [comment]
Just need to finish the main bundler file for this.

**Comment by shawnrice** [comment]
At this point in time, everything is up to date, so I'm closing.
