### ISSUE TITLE
PHP Tests

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#19]
Use [PHP Unit](http://phpunit.de/manual/4.1/en/index.html) for testing.

See #60.
# 
##### Status
- Started writing tests
- Need to rewrite tests with PHPUnit
###### AlfredBundler

Some (indirectly-ish)
###### AlfredBundlerInternalClass

Some
###### AlfredBundlerIcon

Most
###### AlfredBundlerLogger

None

**Comment by deanishe** [comment]
No hurry … :wink:

**Comment by shawnrice** [comment]
...

**Comment by shawnrice** [comment]
Things are happening here: 9678ea3ee08c14d88b3dbc2207622a60d79d96a2

**Comment by deanishe** [comment]
Great work on that. Did you find any bugs?

**Comment by shawnrice** [comment]
I added a checklist to issue #60 about creating tests, so I'm closing this issue. To keep track of the progress there.
