### ISSUE TITLE
Webfonts/icon sets

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#20]
Should we add [Octicons](https://octicons.github.com/) (Github's own icon font) to the supported icon sets?

**Comment by stephen-bunn** [comment]
We should add as many icon fonts as we can support. I would also like to recommend [OpenIconic](https://useiconic.com/open/) as an addition to the supported icon fonts. (If it's not already implemented)

**Comment by deanishe** [comment]
Had a quick look and both should be possible. 

I'll look into it. 

Any webfont with appropriate licensing should work. 

Here's how to configure/package a font:
https://github.com/deanishe/bundler-icon-server/blob/master/README.md

**Comment by deanishe** [comment]
I've [added Octicons](http://icons.deanishe.net/preview/octicons). Unfortunately, I have to work now. I'll try to add OpenIconic this afternoon.

I'll put the individual icon packs in [this repo](https://github.com/deanishe/bundler-icon-server-iconpacks).

**Comment by shawnrice** [comment]
Dean: Awesome. And take your time on everything. Paid work comes first. 

Rita: feel free to work with Dean's repos by following the scripts and putting in pull requests.

**Comment by deanishe** [comment]
Added OpenIconic, too.

Good spot, Rita.

Are there any other webfonts that can go in there?

**Comment by deanishe** [comment]
I changed the name of this issue to make it a general thread for discussing new webfonts to add.

**Comment by shawnrice** [comment]
Sounds good.

**Comment by stephen-bunn** [comment]
These are the most frequent fonts (that I've seen) used, http://weloveiconfonts.com/. I don't exactly know the licensing of them all at the moment, but most of them should be open.

**Comment by deanishe** [comment]
Bloody hell. There are _loads_ of them.

I don't have much experience of using webfonts.

Does anyone more knowledgeable have any particular recommendations regarding which ones to include?

My reading of the licences is that, in almost all cases, it's okay to use them on the server, but some of them can't be included with the server source (i.e. redistributed).

**Comment by shawnrice** [comment]
Well, if we add too many more icon fonts, then they are less likely to be re-used. We're already including six icon fonts, which amounts to... uh... lots of icons. We might consider capping the offerings here, or maybe adding a few more at most. It's a sort of being overwhelmed with choices thing. If there are any more "unique" fonts that either provide non-standard icons that could be useful or ones that are an entirely different aesthetic, then could put those in there.

Of course, add as many as you like, but we don't need to feel compelled to include all that we can.

**Comment by deanishe** [comment]
Agree with that. There are over 1000 icons there already, and a lot are "duplicates".

I'd like to add one of the weather icon fonts. Are there any other similar niche icon sets?

I suppose a search function on the server might be a good idea, too.

**Comment by shawnrice** [comment]
One thing we could always do is just to put a note on the page that says something like "if there is a niche icon set that you think should be included, and if it follows these licensing guidelines, then open an issue HERE"

The issue queue could then link either to this repo (probably better) or to the icon server repo.

**Comment by deanishe** [comment]
Good idea.

I'd prefer to link to here, as there are icon sets we can put on the running server, but not include with the source code (my interpretation of "no redistribution permitted").

**Comment by shawnrice** [comment]
Sounds good. Let's do that.
