### ISSUE TITLE
Python Coding Style

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#21]
The current Python wrapper code is compliant with [PEP 8](http://legacy.python.org/dev/peps/pep-0008/).

While I've always been a TAB rather than spaces man, PEP8 is the _de facto_ Python style guide, and adhering to it will encourage contributions. Plugins to verify compliance are available for most decent editors.

As a result, I believe there is no compelling reason to _not_ follow PEP 8, and we should therefore strive to write PEP 8-compliant Python code.

**Comment by shawnrice** [comment]
I noted that in the README file for devel.

**Comment by stephen-bunn** [comment]
Agreed. Sphinx documentation can easily be applied to PEP257 standards as well.

**Comment by deanishe** [comment]
There is a [numpy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) extension for Sphinx that can parse PEP 257-like docstrings.

The existing wrapper is documented in standard ReST (though that can be changed).

What I haven't figured out is a simple way to extract that into a single, simple HTML file that can go with the rest of the documentation.

**Comment by shawnrice** [comment]
Since it's up to standards. Let's close this.
