### ISSUE TITLE
Install Assets with Native Code

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#24]
The Ruby (and I think Python) bundler currently uses the `alfred.bundler.misc.sh` script to install assets. Since native code is faster, installation functions need to be written for both of those languages.

The install process : 
1. Load the JSON (first try to use provided JSON, then fallback to defaults, then fallback to error);
2. Download the files to the cache directory;
3. Unzip/untgz, etc... depending on the 'method' defined;
4. Use system calls to execute each installation step;
5. Delete the cache installation directory;
6. Call gatekeeper if necessary (system call);
7. Return the path.

We can review the installation process if we think that there is a faster / better way to do it. Right now the alfred.bundler.misc.sh outsources the JSON handling to a PHP script that does much of the processing.

There are a few flags to note: __DATA__, __CACHE__, and __FILE__. These strings are replaced dynamically by the installation script.

**Comment by deanishe** [comment]
The Python wrapper uses the misc wrapper to do the heavy lifting.

It also caches the paths returned by the bash script, so the misc wrapper is only called once for any given asset.

The caching makes the performance issue largely moot, IMO. It's going to take a few seconds to install a new utility whatever we do, and once the Python wrapper has cached the resulting path:

```
Calling `bundler.init()`
10 calls in 0.0395 s (0.0040 s/call)

Calling `bundler.utility("Pashua")`
10 calls in 0.0002 s (0.0000 s/call)
```

(`bundler.init()` is the Python-specific dependency installer/initialiser.)

The main advantage I see in native bundlers is more appropriate error handling.

Having fully native bundlers would definitely be better, but is it really a release-blocking issue or more of a "would be nice to have"?

My personal feeling is that, in any case, this is something we should consider leaving till the very end, when we've got any and all bugs worked out of the standard bundler.

**Comment by shawnrice** [comment]
I'm convinced. Removed the release blocking tag (feel free to futz with these tags on your own).
