### ISSUE TITLE
Treat misc bundler as executable

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#27]
Going with the adopted coding standards and practice, the misc bundler is an executable while the bash bundler is a library.

We need to rewrite it as such.

Should we keep it in "wrappers," or should we put it elsewhere (as it isn't really a wrapper).

**Comment by deanishe** [comment]
I suppose it's technically not a wrapper, but it performs the same function as the wrappers (or performs their functions for them), so I reckon we should leave it in there.

There isn't an obviously better place for it (IMO).

**Comment by shawnrice** [comment]
Okay. I'm good with that. But, on the bright side, since it's an executable, we don't need to make all the function names longer to avoid clashes.
