### ISSUE TITLE
Argument Order (for load and for icons)

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#30]
@deanishe and I decided to change the argument order for the load functions and the icon functions.

The generic load call should be `load( TYPE, ASSET_NAME, VERSION, JSON )` where `version` is optional and should default to `default` and `json` is optional and should default to empty.

The icon call should be `icon( FONT, NAME, COLOR, ALTER )` where `color` and `alter` are optional. `color` should default to `000000`, and alter should default to `FALSE` (unless `color` and `alter` are both empty, in which, `color` defaults to `000000`, and `alter` defaults to `true`).

Use this issue to track the changes:
#### Load function
- [x] Bash
- [x] Misc
- [x] PHP
- [x] Python
- [x] Ruby
#### Icon Function
- [x] Bash
- [x] Misc (inherits from Bash)
- [x] PHP
- [x] Python
- [x] Ruby
#### Other scripts to be altered

I know there are other ones that hook into these, but let's list and track them here.

**Comment by deanishe** [comment]
Python version done.

**Comment by shawnrice** [comment]
Finished.
