### ISSUE TITLE
Notify

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#32]
Each bundler, except bash (and misc), should have a nice "notify" function that will let people easily tap into **cocoaDialog**. The code saved for the bash one just isn't enough to make sense.

Each should tap into the native bindings that @Ritashugisha wrote (`bundler/includes/bindings/terminal-notifier/...`).
#### Completion
- [x] PHP 
- [x] Python
- [x] Ruby
#### Install CocoaDialog instead of Terminal Notifier on installation
- [x] Bash
- [x] PHP
- [x] ~~Python~~ (sensibly delegates heavy lifting to somebody else's script)
- [x] Ruby

**Comment by stephen-bunn** [comment]
The cocoaDialog bindings also have a notify function that allow the user to use their own icons and change the color of the notification. Unfortunately, cocoaDialog's notify doesn't link to Notification Center.
This notification is built off of the GrowlSDK and is built into cocoaDialog so there isn't any need to install Growl to use these notifications (as documented).

This may be a solution to our problem with using our own icons in TN. Unfortunately, Growl doesn't really have the versatility of TN when it comes to clicking on the notifications.

**Comment by shawnrice** [comment]
How often do you think that people use the triggers when clicking on notifications? I've used them only once with the Packal Updater workflow (tied into Alfred Cron). How much use do people make of these?

If they're an edge case, then it seems like it would be worth using Cocoa Dialog over Terminal Notifier because people would get much more excited about using their own icons than those who would take advantage of the trigger functionality. And, honestly, the notification center, for me, is just something that is a bloat feature in OS X and not worth holding onto and thus not an argument in favor of TN.

I chose TN over CD for the simple reasons that it seemed easier to implement and that I was familiar with TN and not CD, and those are not good reasons to stick with TN if CD is the better choice.

**Comment by stephen-bunn** [comment]
It depends what people think of the look of the notification.
If you choose to disable growl for the notification you can edit the notification's color. Alpha values, background, border, and text colors are all up for grabs.

![screen shot 2014-08-01 at 2 18 20 pm](https://cloud.githubusercontent.com/assets/4956855/3783027/78fe90a0-19a8-11e4-80e5-afed6baaaef8.png)

If you choose to leave growl enabled, the notification defaults to whatever your growl style is. This will remove manipulation for colors, but still allow you to use your own icons.

![screen shot 2014-08-01 at 2 22 51 pm](https://cloud.githubusercontent.com/assets/4956855/3783074/de4dee10-19a8-11e4-82f4-3dc7c69ea07a.png)

**Comment by deanishe** [comment]
What's going on now wrt notifications? Does the bundler no longer install Terminal-Notifier by default?

**Comment by shawnrice** [comment]
It still does install it, but we should change that and install CD instead.

After we create the `notify` function in each bundler, that function should be used to display the "successfully installed alfred bundler" message. So that will need to be put into the PHP, Ruby, and Bash wrappers.

We still need to decide on the default styling for the `notify` function as well.

**Comment by deanishe** [comment]
I was confused. It doesn't appear to be installing anything at the moment :frowning:

Have you tinkered with the bash installation code? As far as I can tell, it no longer installs utilities.

**Comment by shawnrice** [comment]
Might have. I'll double check now.

**Comment by shawnrice** [comment]
Okay. It's working now as long as you use the environmental variable. So, before you execute the code, do:

`export ALFRED_BUNDLER_DEVEL='devel'`

**Comment by deanishe** [comment]
The problem was the arguments were messed up in the misc wrapper. Working now.

**Comment by deanishe** [comment]
I edited the OP to put Python back in the second list. It _does_ rely on the misc wrapper, but due to the way the wrapper works, it asks it for `Terminal-Notifier` in order to kick start installation. I'll change this to `CocoaDialog` when the shell bundler has been changed.

Actually, I should probably change it to use the normal bash wrapper for installation…

**Comment by shawnrice** [comment]
Oh, right. I forgot that I changed it so that the misc bundler could load icons...

I figured it was a good change to provide icons for title case servers and AppleScript workflows.

But totally forgot that it fucked up the everyone else's syntax.

**Comment by deanishe** [comment]
No problem. It did take me a fair while to figure out, but ain't nobody never got no title case servers for free.

**Comment by deanishe** [comment]
I've rejigged the Python wrapper/interface to use the standard bash wrapper (not the misc one) to do the install.

Sad that it took the drafting of my earlier message for the penny to drop…

As a result, I was able to remove the Python wrapper/interface's custom install of the misc wrapper (and its update check thereof).

Now it uses the misc wrapper from the installed bundler to do its sexy thang.

**Comment by stephen-bunn** [comment]
Have we decided on a common notification style? I know that we were talking about trying to copy Yosemite's new notification style, but Yosemite's new notifications have levels of alpha and a fair amount of Gaussian blur (which is impossible to add through CD).

So should we stick with Mavericks (white / light gray) notification style? Or should we **try** to copy Yosemite's style?

**Comment by deanishe** [comment]
I'd just leave it as is. Trying to emulate Yosemite will just make stuff look wrong on Mavericks and vice versa.

On my machine, I just let `cocoaDialog` use Growl: regardless of whether or not it looks _just_ like "native" notifications, it's a notification style I'm used to seeing.

**Comment by shawnrice** [comment]
I think this is done. Is it done in Python? (closing).
