### ISSUE TITLE
Standardize Error Messages

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#35]
I'm finding myself writing error messages in a few different ways — especially between different implementations of the bundler, and I'm starting to notice (my own) inconsistencies, so I'd like to start a discussion to standardize error messages.
### STDERR v STDOUT

First, we should make sure that all error messages are sent to STDERR.
- Bash: `echo "<error message>" >&2`
- PHP: `file_put_contents( 'php://stderr', "<error message>" );`
- Ruby:`STDERR.puts "<error message>"`
- Python: `sys.stderr.write('<error message>')`

**However**, sometimes the error message needs to be put to STDOUT when a function calling it needs the output of the error message and a simple exit status will not suffice. These need to be identified.
### STDERR: _error_ v _warning_

**Fallbacks**: Output sent to STDERR doesn't necessarily mess up a script filter in Alfred (this might need verification), so, when we provide fallbacks (such as the backup broken IE icon: #8), we should send a warning to STDERR.

**Bundle IDs**: The bundler is supposed to work with Alfred, and so we should be able to find an `info.plist` to use for certain things such as gatekeeper messages, the registry, automatic icns generation, etc.... Not being able to find a suitable `info.plist` should issue a warning.

**Errors**: we need to determine the threshold at which an error is non-recoverable and should shutdown the script. For the `install` function in the bash bundler (see `bundler/wrappers/alfred.bundler.sh`), when the bundler cannot be installed, the script sends kills the overall script that called it. That might be a bit harsh.
### Syntax

The inconsistencies arose out of the syntax for the error messages. Should we indicate "Error:" or "Bundler Error:"?  Should we use all caps: "ERROR: <regular error message>"?

**Comment by stephen-bunn** [comment]
We could even go a little deeper than "ERROR" if we wanted to. Maybe provide a traceback, or something helpful to people using the bundler. If anything we should distinguish ourselves from the other error messages that occur. So something like "BundlerError:" would work best.

**Comment by shawnrice** [comment]
From my understanding, traceback is much easier in Python and Ruby because that functionality is basically baked in. For PHP and Bash, however, it's not as clear cut, so we'd have to "fake" a traceback functionality.

Can you flesh out the idea more of what we'd provide as traceback functionality?

**Comment by stephen-bunn** [comment]
Nothing extremely complex, just whenever we encounter a **critical** error, we should provide the user with some information on what functions were called and where we ended up.

I don't know the depth the [getTrace](http://php.net/manual/en/exception.gettrace.php) exception works in (for PHP), and I know in order to provide something for Bash we would need to build a [custom function](https://gist.github.com/docwhat/5889193).

 But for the languages that support it natively, we should at least provide an option to toggle tracebacks on and off for debugging.

**Comment by shawnrice** [comment]
Now I realize that I should have known about getTrace.

We can do some more testing with those bash concepts and see how they play out when a library (AlfredBundler.sh) is included (in alfred.bundler.sh) and further included (in the place the workflow author implements the bundler). 

We'll also have to figure out how well it plays when passing information back.

Another option would be to log more often and more effectively. I added a log function in the PHP bundler, and we could include a parity version in all the bundlers as long as we establish a logging scheme.

**Comment by stephen-bunn** [comment]
I'm up for more logging. Give your input here [#37](https://github.com/shawnrice/alfred-bundler/issues/37). 
With more strength in our logs, we could move all non-critical logs to a single file for each workflow. 
We would also have to provide a way to view and remove these logs in the manager workflow.

**Comment by shawnrice** [comment]
Single file workflow error logs could be good, actually. We should store them as `error-bundleid.log` and redirect any non-bundle logs to `error-nobundle.log` as the catchall. It might be useful to put in even critical information to these logs. The general `error.log` file would then be for meta-bundler errors -- problems with the bundler itself.

Actually, thinking aloud, would we want to make the logging function available -- in general -- to the workflows themselves? If a bundle id were present, then we'd just output the line to `{alfred-data-dir}/{bundle-id}/logs/{logname}.log`. It would be a nice little developer feature for creating logs, but the perennial question is then raised: _is this a function for the bundler or for Alfred libraries to implement?_

Possible call-spec for PHP user logging:
`$b->log( $logLevel, $message, $logName="$bundleid" );`
I'd then remap the current `log()` method to be a private `internalLog()` method.

**Comment by stephen-bunn** [comment]
I like the idea of giving the developer their own private log. Although, even if they are beginners at building workflows, they could implement this themselves. Nevertheless, we should include a logging function that can save the developer time in building his/her own logging feature.

Note, if we allow this feature, we should be _very_ distinct which log is an AlfredBundler log, and which log is the developer's log.

**Comment by deanishe** [comment]
Output to STDERR will not mess with Alfred. It will be shown in the debugger, though.

`print('message', file=sys.stderr)` is how I'd normally do it on Python (no need to add a line break).

I've added logging to the Python bundler and wrapper. There's an internal logger and a user-facing function to generate their own logger.

I remain against sending error messages to STDOUT and especially against killing any processes that aren't bundler subprocesses. It's entirely inappropriate for a library/utility to kill its caller.

WRT to the former, I suspect other coders are no better about checking exit codes than we are, so better to output an error message to the appropriate place immediately than to send back an error message on STDOUT that might be mistaken for valid output.

**Comment by shawnrice** [comment]
I agree about sending error messages to STDOUT. Any error messages that are currently printed there need to be changed.

**Comment by fractaledmind** [comment]
So, for Bash and AppleScript at least, there are specific error numbers. I know we want both consistent and meaningful error messages and numbers, so what are the errors? Should I simply mirror Bash? The file says that this is still in flux, which is why I'm asking.

**Comment by shawnrice** [comment]
Since AppleScript uses error numbers like Bash does, then they should use them as well. Ruby has named errors, so it uses that. If the languages support the error numbers, then they should use them; otherwise, not.

The numbers seem to have solidified at least enough for now. We threw them into error "ranges" so that we could expand them later if needed in a way that wasn't entirely arbitrary.

**Comment by fractaledmind** [comment]
Where can I find the stable "ranges" and specific error numbers?

**Comment by shawnrice** [comment]
Look near the end of #62.

**Comment by fractaledmind** [comment]
#62 cannot be what you meant to reference...

**Comment by shawnrice** [comment]
Nope. Meant #42.

**Comment by fractaledmind** [comment]
Ok. I've brought the AppleScript bundler in line with those guidelines.

**Comment by shawnrice** [comment]
This should be done. Closing.
