### ISSUE TITLE
Better Plist discovery

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#38]
Currently, the bundler needs to assume that the wrapper will be located in either the workflow root directory or one level above the workflow root directory. Hence, current behavior looks for `info.plist` and falls back to `../info.plist`. Finding none, it assumes there is no plist available.

We could add in other functionality in that the workflow author provides the path to the `info.plist`, optionally. This behavior is partially baked into the PHP bundler for testing/development purposes.

Adding the plist file is easy enough with modern languages (instantiate them as a property of a class object or the like), but harder with Bash. Hence, we could just not implement the latter feature with bash.

So, let's quickly decide what to do here and close out the issue:
1. Require that the bundler wrapper be in either the root of the workflow directory or one level above;
2. Allow the bundler to be passed a path to an `info.plist` file (excluding Bash); or
3. Do something more radical.

My current vote is to implement 1 and 2 and not bother for 3.

**Comment by stephen-bunn** [comment]
+1 for 1, I don't really see the benefit of allowing a custom plist path. If we did allow this it would be very easy for a developer of a workflow to build a lookback function and grab an info.plist from another workflow.

**Comment by deanishe** [comment]
The Python wrapper looks in the current working directory for `info.plist` and then in its parent and its parent etc. (throwing an Exception if it reaches `/` without finding an `info.plist`).

This is based on the (imo, reasonable) assumption that the wrapper will be somewhere within the workflow's directory and not above it.

How would a wrapper end up _above_ the workflow directory (and therefore above `info.plist`)? Wouldn't that mean it's not in the `Workflow.alfredworkflow` file?

**Comment by shawnrice** [comment]
It's a matter of how the library is included / where we're looking for the info.plist.

As long as the script is running from the workflow root, then looking in "../info.plist" would obviously be pointless, but if someone has put the script in "workflowroot/libraries," then we might need to look below. I'll/we'll have to review where the calls are in the code to see what behavior will happen.

**Comment by deanishe** [comment]
> if someone has put the script in "workflowroot/libraries," then we might need to look below

Do you mean "above"? As far as I can tell, the wrapper cannot be above `info.plist`, i.e. in a parent directory of `workflowroot`, only below. Hence the behaviour of the Python wrapper.

**Comment by shawnrice** [comment]
I get turned upside down and so my prepositions don't work correctly when talking about filesystems.

**Comment by shawnrice** [comment]
This seems to be moot now. We just don't let the bundler work unless an "info.plist" file exists.
