### ISSUE TITLE
Public Log Functions

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#39]
From issues #37 and #35, the idea of a public log function has been introduced.

The bundler would still maintain its own, internal logs, but it would also make logging functionality available for the workflow authors.

Proposal:
Each bundler implements its own bindings for a `log` function. This log function is then divided into `log_internal` and `log`. The internal logs are always placed in `data/logs/<logname>.log`; and the external logs are always located at `<alfred_data_directory>/bundleid/logs/<name.log>`.

The external logging functions will be unavailable if a bundleid is unavailable (this issue is linked to #38).

**Comment by shawnrice** [comment]
I'm kind of doing a sprint here, apparently...

Anyway, preliminary log functionality has been implemented into the PHP bundler. Here is the snippet: `log( $message, $level = 0, $log = 'info' )`. The log function exits with a message to STDERR if no valid plist has been found that will allow the bundler to identify a bundle id.

Public logs have a limit of 5000 lines.

The original bundler log function has been renamed to logInternal.
Bundler logs still have a limit of 500 lines.

**Comment by deanishe** [comment]
Added to Python bundler.

**Comment by shawnrice** [comment]
Added to PHP (see #37 for commit hashes).

**Comment by shawnrice** [comment]
Added to Bash and Ruby.
