### ISSUE TITLE
osascript error

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#40]
I don't recall this error occurring on my computer, but on the one I'm using now, the `osascript` called from gatekeeper gives me this error:

```
2014-08-01 20:05:06.394 osascript[28065:507] Error loading /Library/ScriptingAdditions/QXPScriptingAdditions.osax/Contents/MacOS/QXPScriptingAdditions:  dlopen(/Library/ScriptingAdditions/QXPScriptingAdditions.osax/Contents/MacOS/QXPScriptingAdditions, 262): no suitable image found.  Did find:
    /Library/ScriptingAdditions/QXPScriptingAdditions.osax/Contents/MacOS/QXPScriptingAdditions: mach-o, but wrong architecture
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" declares no loadable handlers.
```

It doesn't seem to affect the display of the dialog at all, and it doesn't seem to affect the functionality, so, should we worry about it?

**Comment by shawnrice** [comment]
See if you can duplicate just by running:

```
osascript -e 'display dialog "A workflow that you have downloaded uses the Alfred Bundler to install required support software, and it wants to use 'viewer.' Will you allow it? If you press 'Allow,' then you will be prompted to enter your password, which will grant access to this application. " buttons {"Allow","Deny"} default button 1 with title "Alfred Bundler"'
```

**Comment by stephen-bunn** [comment]
I didn't receive any errors from this. I did quick Google and only a few useful things popped up.
http://hintsforums.macworld.com/showthread.php?t=114118

Nothing really that helpful, but it might help determine what is going wrong.

**Comment by shawnrice** [comment]
I'm going to assume that the error is unlikely, and since it generates a warning and doesn't alter the functionality, then we can just ignore it.
