### ISSUE TITLE
Error handling/behaviour

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#42]
I've been poking around in the Taurus bash bundler/wrapper, and I think we need to have a proper think about the error handling.

In particular, I think this (from the shell wrappers) is sub-optimal:

```
kill -s TERM $TOP_PID
```

IMO, the bash bundler and wrappers should return _documented_ non-zero exit statuses if something goes wrong instead of just dying. That way, workflows (and other wrappers) using them can behave appropriately depending on what went wrong, e.g. show/log an error message, try again.

As a start-off suggestion:
- 0 — exited cleanly
- 1 — unspecified error
- 2 — incorrect arguments passed to bundler function/wrapper
- 3 — download error (couldn't connect, corrupt file)
- 4 — bundler installation error (a sub-error of `3`, but arguably more critical than a failed icon install)
  …

Also, there's currently no verification of whether the downloaded zip extracted okay. I suspect this was the cause of Stephen's problem documented [here](http://www.alfredforum.com/topic/4255-alfred-dependency-downloader-framework/?p=28651).

The bundler needs to be able to recognise and back out of any failed installation, as it has an uncommonly large scope for breaking shit and is also tricky to fix (without deleting the whole thing).

**Comment by shawnrice** [comment]
The assumption that I had was that if the bundler couldn't be installed, then the workflow just wouldn't work. But, that assumption might have been a bit over-reaching or paternalistic. 

We can take that out. We can also add in a test to make sure that the zip file is valid before continuing. 

For the error codes: `2` might need to be split to indicate the difference between a `recoverable error` and a `fatal error`. 

Two examples of the `recoverable error`:
1.  would be that they ask for an icon with a color that isn't a valid hex. Currently (in Bash and PHP) the icon functions log an error and return nothing. But, it should probably return a context-appropriate color of the icon, and just download that icon. This is a recoverable error that includes incorrect arguments passed.
2. there is a request for a system icon that does not exist, and, so, they get back the broken IE icon. Those are incorrect arguments, but (embarrassingly) recoverable.

Now, an irrecoverable error would be to try to load an asset that cannot be found. Examples:
1. author tries to load 'Cocoa Dialogue', which obviously cannot be found; or
2. author tries to load a custom asset with bad json.

We should keep the technical names of the ones above, but for our purposes here, to re-frame the above exit codes, less technically, the above would be
0. Success
1. Error
2. User error
3. Connectivity Error
4. (again, subset of 3)

It might be good for us to give ourselves a bit more room with the error codes:
- 0: Success
- 1–9: Internal Error
- 10–19: User Error
- 20–29: Connectivity Error

If we have those spans set aside for exit codes, then we could refine these as necessary through minor versions of the bundler.

We'll need to go back through all the functions to make sure that the correct error code is passed back to the user.

**Comment by shawnrice** [comment]
(854f0921473980fbb73e98fe40ec7316268bd23c) Added in quick fix to test for a corrupted zip in the bundler installation. We'll alter it after we sort this issue better.

**Comment by deanishe** [comment]
I'd advise against different codes for recoverable/unrecoverable errors: I think only the user is in a position to decide what is a recoverable error and what isn't: We have no way of knowing if they're using `cocoaDialog` to get essential input from the user or to show a progress bar.

I like your names better.

If you think we might need much more specific error codes, we can separate them out a bit more. It doesn't make the implementation more complex.

**Comment by shawnrice** [comment]
I'm inclined to agree about the difference between recoverable and unrecoverable errors; the logs and error messages can specify more information, but the exit codes should remain the same.

For further error codes, some specificity might help.

The difference between a connection timeout and a corrupt download might need to be handled differently on how the user would want to show the error. I know that for the Packal updater, I ended up needing a difference between no and limited connectivity. While I don't see a case where the bundler would need to know the difference, it might just be that I don't see it yet.

For now, let's just keep the ranges available and use the lowest number in the range until we determine that we need a difference. 

So:

```
Range: (0)
0 : Success

Range: (1–9) Bundler Errors
1 : Unspecified Error

Range: (10–19) Workflow Author Error
10 : Bad arguments sent, recoverable
11 : Bad arguments sent, irrecoverable

Range: (20–29) Bundler installation / connectivity errors
20 : Connectivity issue, no internet connection
21 : Connectivity issue, could not connect to server
22 : Connectivity issue, corrupt download file
23 : User canceled bundler installation
```

**Comment by shawnrice** [comment]
Should be done.
