### ISSUE TITLE
Color Caching

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#45]
I've noticed that the color conversion for icons in Bash is somewhat slow, so I'm implementing a "color-cache"; basically, if argument to alter a color is thrown, then it executes the function and stores the result in `data/color-cache`. A file is saved as the original color name and the contents of said file is the color conversion. This should speed things up in bash, and, potentially in other bundler.
##### Implement color caching for...
- [x] Bash
- [x] PHP
- [x] Python
- [x] Ruby

**Comment by shawnrice** [comment]
Initial implementation in PHP and Bash done. It looks like it speeds things up, but I didn't do any real testing.

**Comment by deanishe** [comment]
Also implemented in Python

**Comment by shawnrice** [comment]
We need to alter the implementations in regards to #52.

**Comment by shawnrice** [comment]
I actually haven't implemented this in Ruby, but it's going so incredibly fast, that I don't think I need to do so. The cache was most important for Bash.
