### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#47]
I notice you guys are using the GPL v. 3 licence for your code.

I prefer the MIT licence for mine. Is that a problem?

**Comment by shawnrice** [comment]
It should be the same throughout. What is your preference for MIT over GPL here?

**Comment by deanishe** [comment]
GPL is _way_ more restrictive. "Viral" if you believe Microsoft.

I'm quite happy for anyone to do as they please with _my_ code, as long as they give me credit.

GPL v.3 largely forces anyone who uses the code to also release their code under the GPL. Even if a user isn't strictly bound by the terms of the GPL, they may steer clear to avoid any doubt. For example, the author of something like the Dash workflow, which is a relatively trivial add-on to the main app, might be put off from using the bundler due to potential licensing problems.

The bundler isn't exactly something that a third party could wrap up and sell, so I don't see a lot of benefit in going with the GPL to prevent that.

Any workflow author using the bundler will feel obliged (and is possibly legally required) to also license their workflow under the GPL. They can, of course, also release their own code under any other licences they want to, but only _in addition to_ the GPL.

By using the GPL, we're potentially excluding any developers of paid apps from creating a complementary Alfred workflow based on the bundler.

I think this is excessively restrictive, and I'd sooner see additional non-GPL workflows based on the bundler than fewer workflows based on the bundler purely because we chose such a restrictive licence.

At any rate, having some MIT-licensed code within a GPL-licensed project isn't inherently a problem: the MIT licence is more liberal, so it doesn't in any way further restrict what a user can do with the bundler code. And it's not like someone could take the Python code, go HAHAHAHA!, and do an end-run around the rest of the bundler.

It would only be an issue if one of you guys added some code to the files I've written and objected to such a liberal licence.

That said, it would make me feel somewhat uncomfortable licensing my code under the GPL.

That's a Linux, everything-must-be-free, idealogue thing. MIT is much more common for free OS X libraries: it allows people to use your code _and also charge_ for their end product, instead of having to give it away, too.

For me, getting the bundler out there is more important than foisting my belief in open source software on others.

I can't really see a situation where the majority of the value of a workflow is provided by the bundler, which would be, imo, the main argument for using the GPL (i.e. preventing others from cashing in big time on our work).

**Comment by shawnrice** [comment]
I hadn't thought of things like Dash. Okay. That works. I'll change it.

**Comment by shawnrice** [comment]
Thinking on it a bit more, I'd rather not have the copyright in the MIT license be split between bundler files.

So I'd propose that we just have the license beginning read:
`Copyright (c) 2014 Shawn Rice, Dean Jackson, Stephen Bunn`

After all, the inner workings of the bundler are so intertwined that having the copyright attribution to different people on different files just seems weird. Plus, I'd argue that a decent amount of the code has been co-written, and the logic between them all has been a group effort, so each file is really a collaborative effort.

Would that be okay?

**Comment by shawnrice** [comment]
Or `Copyright (c) 2014 The Alfred Bundler Team` (Fun!), and then we define the team in the README/documentation

**Comment by deanishe** [comment]
> That works. I'll change it.

How does Stephen feel about that? Some people have very strong feelings wrt licensing.

> Or `Copyright (c) 2014 The Alfred Bundler Team`

We should probably come up with a standard header that goes in all the files. Something like:

```
This file is part of the Alfred Bundler, released under the XXX licence.

Copyright (c) 2014 The Alfred Bundler Team

See https://github.com/shawnrice/alfred-bundler for more information.
```

**Comment by shawnrice** [comment]
Looks like he always goes with GPL v3, so we'll wait for him to weigh in on this before permanently changing it.

**Comment by stephen-bunn** [comment]
In the past I've only used GPLv3 for the reason that I basically knew it by heart. But I don't mind using a different license at all.

And I do think that we should create a standard header for all files as @deanishe suggested. Also, sorry I haven't been able to weigh in on these issues. I've been really preoccupied with work.

**Comment by shawnrice** [comment]
Don't worry about weighing in too timely if you have work. Paid work / school work comes before this stuff. 

So let's go with MIT then.

New header as per @deanishe. Now we update lots of files....

```
This file is part of the Alfred Bundler, released under the MIT licence.

Copyright (c) 2014 The Alfred Bundler Team

See https://github.com/shawnrice/alfred-bundler for more information
```
