### ISSUE TITLE
PHP bundler logs far too many deletions on install

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#51]
Whenever I install the bundler, the majority of the log entries are PHP code reporting some cache directory/file it's deleted.

Most of the logged paths are contained within other deleted paths. Would it be possible to just log the deletion of the top-level directory in each case? If `/some/dir` has been deleted, it goes without saying that `/some/dir/more_stuff/…` and everything in it has been deleted.

**Comment by shawnrice** [comment]
We can do that. I put the report function in a recursive rmdir method, so that's why it just log spews so much.

I'll instead attach it to the instance calls. When relevant.

**Comment by deanishe** [comment]
This has been fixed, right? Want to close it?

**Comment by shawnrice** [comment]
It was pseudo-fixed. Now it's 'fixed' in that it was just pulled out. I'll reimplement less obtrusive logging soon.
