### ISSUE TITLE
Emoji (:scream:)

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#54]
You're going to hate me. Let's add in emoji support. (:fearful:)

All the :neckbeard:'s will love it.

Plus, it'll be easy. So, here's the proposal:

Each one gets a method\* something like `emoji('shortname')`. That just needs to load the file: `bundler/includes/emoji.json` and spit out the `emoji` under `shortname`. So, for a PHP array, it will be:

```
public function emoji( $shortname ) {
  $emoji = json_decode( file_get_contents( $this->data . "/bundler/includes/emoji.json" ) , TRUE );
  if ( isset( $emoji[$shortname] ) && ! empty( $emoji[$shortname]['emoji'] ) ) {
    return $emoji[$shortname]['emoji'];
  else {
    return FALSE;
  }
}
```

Then the user would just have to :

```
require_once( 'alfred.bundler.php' );
$b = new AlfredBundler;
echo $b->emoji( 'worried' );
```

Which would output, simply :worried:. Yes?

I pulled together the emoji.json file from a bunch of random sources. It's 89kb, so we could consider caching. In which case, we'd add something to the method (again, PHP) like this:

```
public function emoji( $shortname ) {
  $emojiCache = $this->data . "data/emoji-cache";
  if ( ! file_exists( $emojiCache ) ) {
    mkdir( $emojiCache, 0775, TRUE );
  }

  if ( file_exists( "{$emojiCache}/{$shortname}" ) {
    return file_get_contents( "{$emojiCache}/{$shortname}" );
  }

  $emoji = json_decode( file_get_contents( $this->data . "/bundler/includes/emoji.json" ) , TRUE );
  if ( isset( $emoji[$shortname] ) && ! empty( $emoji[$shortname]['emoji'] ) ) {
   file_put_contents( "{$emojiCache}/{$shortname}", $emoji[$shortname]['emoji'] ); // cache the object
    return $emoji[$shortname]['emoji'];
  else {
    return FALSE;
  }
}

```

*(I know that `method` isn't quite right because not all the bundlers are classed, but, we all know what I mean).

**Comment by deanishe** [comment]
:-1:  Should be a utility, not a built-in, imo.

**Comment by shawnrice** [comment]
You just don't want people to start using emoji?

**Comment by shawnrice** [comment]
Actually... um... this raises a nice question that would be rad:

The code for the emoji is some nice and simple library stuff that follows the bundler utility quite nicely and so, if we consider it `non-core`, then it might be `contrib`. (Wait, did the bundler just become pluggable?)

So, for PHP, I could add a factory interface in which someone could just do something like:

```
$emoji = $b->factory->create( 'emoji', '/path/to/json | or url?' ); // needs to be thought out....
echo $emoji->load('worried');
```

Hm. That would be pretty damn cool.

The emoji `plugin` would then just need to do 

```
class bundler_emoji_contrib implements AlfredBundlerPlugin {
...code...
}
```

Hm....

Would that concept be worth it? Or is it just as easy or possible safer to do :

```
$emoji = $b->library( 'emoji', '/path/to/json' );
$e = new AlfredEmoj;
echo $e->emoji('worried'); // this would be internal logic.
```

There, I'd just be writing an emoji library that would be included and loaded by the bundler.

We should probably stick to the later, not the former right?

Or would a pluggable system ultimately increase performance?

**Comment by deanishe** [comment]
> You just don't want people to start using emoji?

:grinning: I used one in the post you replied to.

It just doesn't strike me as such an important library for building workflows that it should be built it.

You write a lot of workflows. Which of these don't you use in almost every one?
- `emoji()`
- `icon()`
- `library()`
- `log()`
- `utility()`

It shouldn't be implemented as a CLI utility (that'd be daft), but it shouldn't be baked in at the top level of the API, either.

 Perhaps we can create a `contrib` part of the bundler, where non-core, but potentially useful, stuff can go:

``` python
from bundler.contrib.emoji import emoji

q = emoji('question')
```

**Comment by shawnrice** [comment]
I moved the `emoji.json` to `contrib`, but I'm not sure if that's the best place for it. It definitely is non-core, but creating a `contrib` category opens the doors for more `contrib` packages, potentially bloating the bundler and leaving us on the hook for fixing those packages.

We could just divide the bundler into `hardcore` and `softcore`. There, the main functionality that we have until now would be `hardcore`, and then we can also add other things like, well, sparklines to the `softcore` part of the bundler.

Maybe `hardcore` and `softcore` aren't the best names...

**Comment by deanishe** [comment]
> potentially bloating the bundler and leaving us on the hook for fixing those packages

If emoji isn't bloat, I don't know what is… :wink:

> Maybe `hardcore` and `softcore` aren't the best names...

:grinning:  Maybe not.

**Comment by shawnrice** [comment]
How about renaming `contrib` to `extras`? The other possibility is to keep all of the "extras" in another repo.

**Comment by deanishe** [comment]
Fuck it. Just call it `bloat`.

**Comment by shawnrice** [comment]
You're going to be the first to create an all-emoji workflow. Actually, people would probably really enjoy having easier access to emoji via Alfred (e shortname -> copy to clipboard/paste).

Calling it `extras`. Closing temporarily. Feel free to re-open at will/whim.

**Comment by deanishe** [comment]
Had one for ages.

https://github.com/deanishe/alfred-emoji-workflow

**Comment by shawnrice** [comment]
Told you.

Too bad it doesn't use the bundler and it's unwritten emoji functionality.

**Comment by shawnrice** [comment]
Oh, and remember that I can track downloads on Packal. I'll tell you how popular it is.

**Comment by shawnrice** [comment]
Oh. You weren't the first. Just saw that you forked it. I was about to be impressed that you wrote it in 18 minutes. (Unless you had a head start).

**Comment by shawnrice** [comment]
It's not on Packal. That's why I didn't know about it.
