### ISSUE TITLE
Updating Defaults

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#55]
Here's a good question (we might just mark it as "don't care" and close it).

We can update the `defaults` in the `bundler/meta/defaults` directory easy enough with a minor update. Adding defaults is not a big deal; obviously, we should never delete a default. However, we might consider modifying a default.

So, so say a new version of `Terminal Notifier` comes out which is much better than the current `default` version of the tool. We could update the `default` version to a new one, would we then want to update the actual asset in the assets directory?

Is this worth pursuing or is it something that might come too close to breaking workflows using the bundler?

**Comment by deanishe** [comment]
If users are just going to go with `default`, I think they have to expect that the underlying utility/library will change over time.

IMO, the `default` setting should be updated, and the installed asset, too. It's meaning should essentially be `latest`. Which might be a better name for it in that case…

**Comment by shawnrice** [comment]
Okay. Lets rename it latest.  That makes the documentation sounds less dumb (`defaults to latest...` instead of `defaults to default`)

**Comment by shawnrice** [comment]
(#56 tracks the naming issue).

Here is the update logic for this:

When a minor update is run, then a new copy of the bundler is downloaded into the cache directory, and the current `{ab_data_dir}/bundler` directory is replaced with the new one. After that the `update-the-bundler.sh` script is run which contains information on how to alter the data structure of the bundler. Each minor version update gets its own function:
- `one_to_two`
- `two_to_three`
- etc...

So, we just throw the data update logic into those functions.

Since we already have the method, I'm closing this.
