### ISSUE TITLE
Change 'default' versions to 'latest'

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#56]
Suggested by @deanishe at #55. I say we go for it.

Until things are transitioned, this will eviscerate the bundler's ability to function.

So, let's do a task list:
##### Update load functions
- [x] PHP `load`
- [x] \* Bash `AlfredBundler::load`
- [x] \* Python
- [x] \* Ruby
##### JSON
- [x] All the default JSON files need to be updated...

**Comment by shawnrice** [comment]
I think I got most of them.

**Comment by deanishe** [comment]
Done.
