### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#57]
Let's prune some unnecessary branches.

Lets get rid of `master`, `aries-with-icons`, and `devel-env`.

Is that cool, @deanishe?

**Comment by deanishe** [comment]
I think so. It won't break aries, will it?

**Comment by deanishe** [comment]
In fact, can't all the branches but `aries`, `taurus`, `devel` and `gh-pages` go?

**Comment by shawnrice** [comment]
It shouldn't break `aries` unless the `aries` version of the python bundler points to `aries-with-icons`, which I don't think it does.

Confirm that, and I'll 86 those branches.

**Comment by deanishe** [comment]
It shouldn't. I only pushed that for you guys to have a look.

**Comment by shawnrice** [comment]
Done. Closed.
