### ISSUE TITLE
Deprecate alfred.bundler.misc.sh

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#59]
The `misc` bundler is **exactly** the same as the `bash` bundler with the exception of a few lines at the end to load some utilities. That brings in a problem that we have two files to maintain that are just about the same. 

Originally, I separated them as a sort of "user-facing" convenience so that there was that `misc` file for people to use when trying out the bundler with Python or Ruby (or something else), but since the number of workflows that are the something else has been severely reduced because of the Python and Ruby bundlers, let's get rid of the `misc` bundler.

So, my proposal.

Take the extra lines at the bottom of the `misc` bundler, and add them to the `bash` bundler. Then, we just do a simple conditional to see if the bundler was run as an executable (i.e.: ${BASH_SOURCE[0]} == me). If so, the extra code is executed. If not, it is ignored.

Pros: Reduced redundancy, causing fewer places to screw up.
Cons: not too many

**Comment by deanishe** [comment]
Added the necessary functionality to the standard bash bundlet, deleted the misc one, and updated the other source files to point to the standard bundlet.
