### ISSUE TITLE
Unit tests (or lack thereof)

### ISSUE THREAD

**Issue by deanishe** [shawnrice/alfred-bundler#60]
## Checklist
- [x] Bash Tests
  - [x] Assets
  - [x] Icons
  - [x] Install
  - [x] Logging
  - [x] Wrappers (N/A)
- [x] PHP Tests (#19)
  - [x] Assets
  - [x] Icons
  - [x] Install
  - [x] Logging
  - [x] Wrappers
- [x] Python Tests
  - [x] Assets
  - [x] Icons
  - [x] Install
  - [x] Logging
  - [x] Wrappers
- [x] Ruby Tests
  - [x] Assets
  - [x] Icons
  - [x] Install
  - [x] Logging
  - [x] Wrappers
# 

The bundler is getting rather complex now, with a lot of interdependency.

I think we really need to hold off on adding new features and changing old ones until we have a solid set of unit tests in place. Apart from verifying things are working the way they're supposed to, unit tests make it easy to make broad changes to the codebase because they will show you everything your changes have broken.

The PHP bundler, in particular, really needs a decent set of unit tests because every other bundler depends on it. Pushing a broken version of the PHP bundler can potentially break everything.

I've no idea if there's a native unit test library available for bash, but it should be possible to test the bash bundler from one of the other languages.

I spent the afternoon writing a set of unit tests for the Python bundler (`bundler.py` and `AlfredBundler.py`). Code coverage is nominally close to 100%, but that doesn't mean there aren't still bugs…

**Comment by shawnrice** [comment]
I agree. I'll dig into those better tonight. If you want to help with the Bash unit testing, then maybe you could look into 
- [round up](https://bmizerany.github.io/roundup/)
- [assert.sh](https://github.com/lehmannro/assert.sh)
- [BeakerLib](https://fedorahosted.org/beakerlib/)
- [epoxy](https://github.com/spbnick/epoxy)
- [shell2jsunit](https://code.google.com/p/shell2junit/)

to see which is the most promising for us to use? That's not an exhaustive list, just the ones that I had in my notes to look at for this purpose.

**Comment by deanishe** [comment]
I'll do it if you promise to write a PHP test suite :wink:

**Comment by shawnrice** [comment]
Added a checklist up in here.

**Comment by shawnrice** [comment]
PHP tests are basically done. There is full coverage at least indirectly.

**Comment by shawnrice** [comment]
Closing. All of these should be done. New tests need to be written if functionality expands, but this is covered.
