### ISSUE TITLE
Installation Error Handling

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#63]
We need to agree on the behavior for installation failure and make all bundlets follow the same logic. Some questions are here: #49.

Decisions:
1. the user refuses to install the bundler: `throw exception`
2. the user presses the `more info` button on the AS dialog: `kill process`
3. the server is not reachable to download the bundler: `throw exception`
4. the zip file downloaded is corrupt: `throw exception`
5. there is no valid `info.plist` file in the directory: `throw exception`.
##### Implementation:
- [x] Bash
  - [x] refusal to install
  - [x] more info
  - [x] cannot download bundler
  - [x] zip file is corrupt
  - [x] no plist present
- [x] PHP
  - [x] refusal to install
  - [x] more info
  - [x] cannot download bundler
  - [x] zip file is corrupt
  - [x] no plist present
- [x] Python
  - [x] refusal to install
  - [x] more info
  - [x] cannot download bundler
  - [x] zip file is corrupt
  - [x] no plist present
- [x] Ruby
  - [x] refusal to install
  - [x] more info
  - [x] cannot download bundler
  - [x] zip file is corrupt
  - [x] no plist present

**Comment by shawnrice** [comment]
In regards to the first one: for the PHP implementation, I'm currently setting an environmental variable called `ALFRED_BUNDLER_INSTALL_REFUSED` to true. Since the `AlfredBundler` class simply passes everything through to the `AlfredBundlerInternalClass` object, I'm just putting in a statement to intercept that call, report an error, and return `FALSE`.

**Comment by deanishe** [comment]
Throw an error/exception, deleting any temporary files or half-finished installs first if applicable.

Only the workflow author knows how serious the lack of the bundler is.

**Comment by shawnrice** [comment]
Turned this into a checklist for tracking.

**Comment by shawnrice** [comment]
@deanishe : what's the status in the Python bundler on this?

**Comment by stephen-bunn** [comment]
The Python bundler should cover these exceptions as of f235392a66cf8bcfac1d20dc7b2ff0688ab78634.
