### ISSUE TITLE
Bash bundler allows arbitrary version numbers

### ISSUE THREAD

**Issue by fractaledmind** [shawnrice/alfred-bundler#70]
Is this intentional behavior? If I, for instance, pass a version number of 100 for Terminal-Notifier to the bash bundler, it will simply install the latest version under the sub-directory `100`. I can see how this could be on purpose, or an oversight. Just making sure it's on purpose :)

**Comment by shawnrice** [comment]
I'll look into it. I might have put in a safeguard to fallback to latest, but it might be too generous.

**Comment by fractaledmind** [comment]
It's a tricky problem. If the user asks for a version that doesn't exist, you can throw an error, but that could be extreme. If you merely install the latest under `latest` tho, they might not be able to find it later (assuming it would be under `100` for instance). But if you install it under `100` as if that is actually a version, you are perpetuating stupidity. 

So, it's tough. I would vote for throwing an error that states what the current downloadable version is. This would force the workflow author to use proper versions.

**Comment by shawnrice** [comment]
It's supposed to throw an error. So, it's definitely a bug.

**Comment by shawnrice** [comment]
Okay. Wow. That was totally borked.

I've fixed it, kind of. There are a few "hacky" aspects of the code, and it doesn't throw an exception or raise an error; instead, it just logs an error message to the console and converts `version` to `latest`. Throwing the error would have involved changing how most of the bundlers work, which is something that we could always put off. Too many of the bundlers are just so completely tied into the Bash bundler (which is tied into the PHP bundler).

The new version is passing with the Bash, PHP, and Ruby tests, but it's failing with the AppleScript tests. (Failing on Pashua and on the altered icon test), but I think that might be something funky with the tests...
