### ISSUE TITLE
Invalid font creates empty directory tree

### ISSUE THREAD

**Issue by fractaledmind** [shawnrice/alfred-bundler#72]
This isn't a critical bug, but a bug nonetheless. If you try to download a character from an invalid font, the bash bundler (well, actually, `icons.sh` it would seem) still create the `.../icons/{font}/{icon}` directories, tho they are empty. They don't take up space, but this is an aesthetic (and necessarily to some degree a performance) waste.

**Comment by shawnrice** [comment]
All the bundlers do that (as far as I can tell). There might be a nifty little way to get rid of them, but I think that it would be easier, at least for Taurus 1, just to clean them up -- remove all empty folders -- in a maintenance script. (#62).

**Comment by fractaledmind** [comment]
Ah. Well, the maintenance script would certainly solve the problem. And I'm sure it's _much_ easier to pre-create the directory tree before downloading, to ensure there are no errors if you are trying to put data in a place that doesn't exist. 

Sounds good.

**Comment by deanishe** [comment]
> All the bundlers do that (as far as I can tell)

I think I removed this "feature" from the Python version.

One way or another, it's not a biggie as long as empty/invalid icon files aren't being created.
