### ISSUE TITLE
Wrapper Tests

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#75]
@Ritashugisha Can you whip up some tests for the wrappers?

**Comment by stephen-bunn** [comment]
Sure thing, I'll see if I can get them up by the end of this week.

**Comment by shawnrice** [comment]
Sweet.

**Comment by stephen-bunn** [comment]
While writing tests, I ran into an issue where the Ruby bundler's utility method won't install the passed utility if it is missing. The tests should work after this is fixed

**Comment by shawnrice** [comment]
Looks like you got these fixed. Sweet.

The TN tests pass, and the CD tests seem to pass, but I do get this:

```
Finished in 9.652314s, 0.5180 runs/s, 1.5540 assertions/s.

  1) Error:
CocoaDialogTest#test_stoppable_progressbar:
IOError: closed stream
    /Users/Sven/Documents/Alfred2 Workflows/alfred-bundler/bundler/includes/wrappers/ruby/cocoadialog.rb:946:in `close'
    /Users/Sven/Documents/Alfred2 Workflows/alfred-bundler/bundler/includes/wrappers/ruby/cocoadialog.rb:946:in `finish'
    /Users/Sven/Documents/Alfred2 Workflows/alfred-bundler/bundler/includes/wrappers/ruby/cocoadialog.rb:937:in `rescue in update'
    /Users/Sven/Documents/Alfred2 Workflows/alfred-bundler/bundler/includes/wrappers/ruby/cocoadialog.rb:933:in `update'
    testCDwrapper.rb:89:in `test_stoppable_progressbar'

5 runs, 15 assertions, 0 failures, 1 errors, 0 skips
```

Are you getting the same? Is the failure significant at all or something we can just ignore?

**Comment by stephen-bunn** [comment]
You can just ignore that error. Nothing is broken, that specific wrapper has to handle pipes differently from the other wrappers.
