### ISSUE TITLE
Check-in

### ISSUE THREAD

**Issue by fractaledmind** [shawnrice/alfred-bundler#77]
This is just a check-in. Is there anything that I in particular need to do to complete any of my responsibilities? TBH, it's been a while and I've lost track of where I was. I feel like I got the AS bundler all set, but I can't remember.

**Comment by shawnrice** [comment]
I don't think that there is. We're waiting on the Python bundler to be brought up to par with the rest, and I think that I need to fix one or two bugs in the Ruby and PHP bundlers.
