### ISSUE TITLE
Create System Icon Font

### ISSUE THREAD

**Issue by shawnrice** [shawnrice/alfred-bundler#8]
We need to figure out how to deal with different versions (10.6, 10.7, 10.8, 10.9, 10.10). Since new icons are introduced and phased out, we might consider limiting the 'displayed' options to the ones that exist throughout all versions that Alfred supports.
#### Icon Server
- [x] Get 10.10 icons
- [x] Get 10.9 icons
- [x] Get 10.8 icons
- [x] Create display page on icon server
- [x] Create fallback icon
#### Implementation
- [x] Bash
- [x] Misc
- [x] PHP
- [x] Python
- [x] Ruby
#### Further

Need to cement fallback method (discussion) and implement

**Comment by shawnrice** [comment]
I've pulled the relevant data for 10.9 and 10.10, but I don't have easy access to 10.6-10.8. We need to find a way to grab these icons.

**Comment by shawnrice** [comment]
I opened a thread on the forums asking for some help to run the icon script. 

www.alfredforum.com/topic/4676-need-access-to-106-107-and-108/

**Comment by shawnrice** [comment]
Found a copy of 10.8. I'll email that to both of you shortly.

**Comment by shawnrice** [comment]
Here's a good question:

How committed should we be to provide full support to 10.6 and 10.7. I know that Alfred supports these versions, but do we need to commit ourselves to providing full support to operating systems that are five and three years old (respectively), especially when you can upgrade past those for free?

In other words, for the system icons: I think I can find a way to create a VM of 10.6 and another of 10.7 in order to run the script to pull the icons, but that seems like a lot of work for little payoff (and it would reduce the icons that we're "publicizing"). The way Alfred handles icon errors is simply to leave it blank, so there would be no error (just an aesthetic glitch) on older systems if a non-standard icon is used. There would be an error if a user tried to include it in an AS dialog.

So, thoughts? Should we just go with what we've got?

**Comment by shawnrice** [comment]
I just added a file at the base of the devel branch called `system_icons.zip`. Grab that, unzip it. Then open `unified.html` in there to see an overview of the icons that are available and what they look like. After the table of icons, you'll see a list of 200 icons that are shared between 10.8, 10.9, and 10.10, which are probably the ones that we want to make available.

I generated the `unified.html` file with the `unified.php` script. So we can easily edit that to create the base of the static page needed for the icon server to display the system icon font.

**Comment by stephen-bunn** [comment]
I would say that we only need to include the icons we already have. It's very unlikely that anyone would even use icons past Mountain Lion. And people are not going to complain about the bundler missing icons from 3 years ago.

**Comment by deanishe** [comment]
Why do we need all the different icon sets? It'd be useful to have a list of the _filenames_ of the icons on each OS version, but I'm not sure having the actual icons is very important except, perhaps, where they are no longer present on Mavericks/Yosemite.

I mean, it's not like a workflow author will have any control over which version of an icon is shown on a user's computer (seeing as the bundler will just grab whatever is in the system icon directory), so I think one version would suffice for a preview version.

It might even be a good idea to leave out icons that aren't included on all OS versions we wish to support. If we include them all, icon availability becomes something workflow authors need to worry about.

**Comment by shawnrice** [comment]
Yes. I'm all for what you're proposing. What I put together is for our viewing purposes for now.

The "names" on the side of the page are the filenames (sans extension).

So we should put up a display page on the icon server of the ones that appear only on all three systems so that the workflow authors can peruse them when deciding.

**Comment by deanishe** [comment]
What should the bundler do if a workflow asks for an icon that doesn't exist? Return a "broken image" icon? Throw an error? Return an invalid filepath and make it Alfred's problem? (What does Alfred do if you give it an invalid icon/bad path?)

**Comment by stephen-bunn** [comment]
I believe Alfred defaults to the workflow icon if the passed icon doesn't exist. I also believe that that's the way to go with invalid icons. Having a broken icon image would be nice, but using the workflow default would be more aesthetically pleasing.

**Comment by shawnrice** [comment]
If it's in a script filter, then it will just show no icon and fail silently.
If it's in an AS dialog, however, then it will throw an error that would make the dialog fail.
We can easily make it fail to an icns file of the icon.png file (and maybe have one more backup in case there is no icon.png file).

**Comment by deanishe** [comment]
Oops. I hadn't considered that icons could be used in other places than Script Filters…

Do any utilities require an ICNS file rather than a PNG?

Then how about a transparent ICNS file included with the bundler by default? Or a broken image ICNS included by default (I vote for the Internet Explorer one, for lulz)?

If ICNS is a thing, should we add a `format` parameter to the icon functions in the bundler/wrappers?

(And if we're adding format conversion support, then I agree we should fall back to an ICNS of `icon.png` first, and then a default—which should still be the Internet Explorer broken image :wink:)

**Comment by stephen-bunn** [comment]
I know that cocoaDialog and TerminalNotifier don't _require_ a .ICNS. And even if the icon is broken or the icon doesn't exist, that shouldn't break the dialog or notification from showing. 

We should add a format option in the bundlers. If we are going to allow people to create their own resources for the bundler, then we need to add support for gathering icons in ICNS and PNG ( for those resources that **do** require them )

Yes, +1 for the broken IE icon.

**Comment by shawnrice** [comment]
One other use might be if we spoof Terminal Notifier by replacing the icns file with a custom one, or something along those lines.
Other than that, nothing comes to mind.

We can always adjust the `make_icns.sh` script to make it more general. Right now, it takes the input file and then creates the icns file in `{CACHE}/icns/filename.icns`. That would allow the script to be used more.

The PHP bundler has an `icns` method in it that will return the bundle's `icon.png` file as an `{CACHE}/icns/{bundleid}.icns`, generating it if necessary. We could extend that to handle extra arguments as well.

I don't think we should add in a `format` parameter for the `icon` methods. Introducing an `icns` method, which would be used far less, seems like the way to go.

:thumbsup: to broken IE image. Put one in the repo! (`bundler/meta/icons`)

**Comment by shawnrice** [comment]
@Ritashugisha : seems we're always responding at the same time. What do you think _in re_: splitting the icon method rather than adding parameters?

**Comment by stephen-bunn** [comment]
@shawnrice Sounds good to me. As long as we support ICNS in some way (especially for being able to spoof the TN icon).

**Comment by shawnrice** [comment]
So, then I'll put in two scripts that will work as
`make_icns.sh </path/to/image.png> </path/to/image.icns>`
`make_png.sh  </path/to/image.icns> </path/to/image.png>`

For both, the first file must exist, and the second file shouldn't exist (although the directory needs to exist), and it'll overwrite any extant file.

The first is what `make_icns.sh` already is, but I'll adjust it so that the parameters so that the second parameter needs to be the full path, and it'll push it to that path.

Then, we can just call each of those scripts when we need them in the bundlers. And each bundler can have some sort of icns method. Sound good?

**Comment by stephen-bunn** [comment]
❤️ it

**Comment by shawnrice** [comment]
Just pushed them both:
- `bundler/includes/icns_to_png.sh`
- `bundler/includes/png_to_icns.sh`

Both check to make sure they're working on a valid file and that the destination directory exists.

The work with full or relative paths.

**Comment by shawnrice** [comment]
Added a TODO list on the first post. Feel free to edit it.

**Comment by shawnrice** [comment]
Check the new fallback icon in `bundler/meta/icons/default.icns`

It's a least a temporary one.

**Comment by shawnrice** [comment]
Not fully implemented in Ruby, but opening up specific issue for that #58.
